spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    # database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
     url: jdbc:mysql://coma-db.cfgaki8mo8qw.ap-northeast-2.rds.amazonaws.com:3306/coma_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
     username: admin
     password: coma1234
     driver-class-name: com.mysql.cj.jdbc.Driver