spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123
            client-secret: 123
            scope: # google API의 범위 값
              - profile
              - email
              - https://www.googleapis.com/auth/youtube.upload

---
spring.config.activate.on-profile: real

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.cotuber.com/login/oauth2/code/google

---
spring.config.activate.on-profile:
  - local
  - local-real

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
